### ISSUE TITLE
각 코어에 페이지를 분배할때 정확하지 않던 문제

### ISSUE THREAD

**Issue by tkddbs369369** [no-brains/bangonik-searcher#13]
`pages_per_thread = pages_num // num_threads
for i in range(num_threads):
    start_page = i * pages_per_thread + 1
    end_page = (i + 1) * pages_per_thread
    if i == num_threads - 1:
        end_page = pages_num  # 마지막 스레드는 나머지 페이지 처리
    print(start_page, end_page)`

이 코드에는 문제가 있음

쓰레드수가 페이지수의 약수가 아니면 작동하지 않음

예시로 
`
pages_num= 103
num_threads = 4
`
이면 

출력값은 
> 1 25
> 26 50
> 51 75
> 76 103

인 문제가 있음

**Comment by tkddbs369369** [comment]
`a = #페이지
b = #코어
c = a/b
d = []
st = 0
for i in range(b):
    d.append([round(st+1),round(st+c)])
    st+=c`

으로 해결함 처음 코드를 누가 작성했는지는 모르겠지만, 제정신이 아닌 상태에서 작성했음이 자명함

**Comment by karpitony** [comment]
결자해지 ㅆㅅㅌㅊ

**Comment by 5tarlight** [comment]
https://github.com/no-brains/bangonik-searcher/blob/e2d6238d3734a3e9d60d52962f2fbf1b4370844b/main.py#L20-L26

이런식으로 코드 참조 가능
